
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RCONJUNTO = 36;
  public static final int MENOS_GUION = 15;
  public static final int PAR_DER = 11;
  public static final int INTERROGACION = 24;
  public static final int DOBLE_PUNTO = 19;
  public static final int POR = 12;
  public static final int MENORQ = 21;
  public static final int BARRA_INV = 27;
  public static final int PORCENTAJE = 7;
  public static final int COR_DER = 28;
  public static final int ACENTO = 31;
  public static final int SEPARADOR = 6;
  public static final int LLAVE_IZQ = 32;
  public static final int IGUAL = 22;
  public static final int OR = 33;
  public static final int ARROBA = 25;
  public static final int AMPERSAND = 8;
  public static final int EXCLAMACION = 2;
  public static final int COMILLA_DOBLE = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMILLA = 9;
  public static final int COMA = 14;
  public static final int DIV_BARRA = 18;
  public static final int VERGULILLA = 35;
  public static final int PAR_IZQ = 10;
  public static final int ELVACION = 29;
  public static final int GUION_BAJO = 30;
  public static final int LLAVE_DER = 34;
  public static final int PUNTO = 16;
  public static final int MAYORQ = 23;
  public static final int NUMERAL = 4;
  public static final int COR_IZQ = 26;
  public static final int PTCOMA = 20;
  public static final int TEXTO = 37;
  public static final int SALTO = 17;
  public static final int DOLAR = 5;
  public static final int MAS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EXCLAMACION",
  "COMILLA_DOBLE",
  "NUMERAL",
  "DOLAR",
  "SEPARADOR",
  "PORCENTAJE",
  "AMPERSAND",
  "COMILLA",
  "PAR_IZQ",
  "PAR_DER",
  "POR",
  "MAS",
  "COMA",
  "MENOS_GUION",
  "PUNTO",
  "SALTO",
  "DIV_BARRA",
  "DOBLE_PUNTO",
  "PTCOMA",
  "MENORQ",
  "IGUAL",
  "MAYORQ",
  "INTERROGACION",
  "ARROBA",
  "COR_IZQ",
  "BARRA_INV",
  "COR_DER",
  "ELVACION",
  "GUION_BAJO",
  "ACENTO",
  "LLAVE_IZQ",
  "OR",
  "LLAVE_DER",
  "VERGULILLA",
  "RCONJUNTO",
  "TEXTO"
  };
}

